## This file specifies the redirects necessary to avoid 404 errors in SPAs
## See here for more info - https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200